package com.example.examenmariandaria.domain;

public enum Orase {
    AIUD,ALBA_IULIA,ALESD,ALEXANDRIA,ARAD,AVRIG,AZUGA,BACAU,BAIA_MARE,BAIA_SPRIE,
    BAILE_HERCULANE,BAILE_OLANESTI,BARLAD,BECLEAN,BEIUS,BICAZ,BISTRITA,BLAJ,
    BOLDESTI_SCAIENI,BORSA,BOTOSANI,BRASOV,BRAILA,BUCURESTI,BUFTEA,BUSTENI,
    BUZAU,CAREI,CARACAL,CARANSEBES,CAVNIC,CALARASI,CAMPIA_TURZII,CAMPINA,CAMPULUNG,
    CAMPULUNG_MOLDOVENESC,CLUJ_NAPOCA,CONSTANTA,COVASNA,CRAIOVA,CURTEA_DE_ARGES,
    DEJ,DEVA,DRAGASANI,DROBETA_TURNU_SEVERIN,EFORIE,FALTICENI,FOCSANI,GALATI,
    GEOAGIU,GHERLA,GIURGIU,GURA_HUMORULUI,HATEG,HUEDIN,HUNEDOARA,HUSI,IASI,INEU,
    JIBOU,JIMBOLIA,LIPOVA,LUGOJ,LUPENI,MANGALIA,MARGHITA,MEDIAS,MIERCUREA_CIUC,
    MOTRU,NADLAC,NASAUD,NEGRESTI,NEGRU_VODA,NUCET,OCNA_MURES,ODORHEIU_SECUIESC,
    ORADEA,ORASTIE,ORSOVA,OTOPENI,PETROSANI,PIATRA_NEAMT,PITESTI,PLOIESTI,
    PREDEAL,RAMNICU_VALCEA,RASNOV,REGHIN,RESITA,SALONTA,SATU_MARE,SANGEORZ_BAI,
    SEBES,SFANTU_GHEORGHE,SIBIU,SIGHETU_MARMATIEI,SIGHISOARA,SINAIA,SIRET,SLATINA,
    SLANIC,SLOBOZIA,SOVATA,SUCEAVA,SULINA,SIMLEU_SILVANIEI,STEI,TARGOVISTE,
    TARGU_JIU,TARGU_LAPUS,TARGU_MURES,TARGU_NEAMT,TECHIRGHIOL,TEIUS,TIMISOARA,
    TULCEA,TURDA,URZICENI,VALEA_LUI_MIHAI,ZALAU,ZARNESTI,ZIMNICEA,ZLATNA
}
